from enum import Enum

class Category(Enum):
    """
    Category types found on the site for collecting profiles from different fields.
    """
    ACTORS = "actors"
    ATHLETES = "richest-athletes"
    AUTHORS = "authors"
    BASEBALL = "richest-baseball"
    BILLIONAIRES = "richest-billionaires"
    BOLLYWOOD = "bollywood-celebrities"
    BOXERS = "richest-boxers"
    BUSINESS = "richest-businessmen"
    CELEBRITIES = "richest-celebrities"
    CEOS = "ceos"
    CHEFS = "richest-celebrity-chefs"
    COACHES = "richest-coaches"
    COMEDIANS = "richest-comedians"
    COMPANIES = "companies"
    CRIMINALS = "richest-criminals"
    DJS = "richest-djs"
    DEMOCRATS = "democrats"
    DESIGNERS = "richest-designers"
    DIRECTORS = "directors"
    EXECUTIVES = "business-executives"
    GOLFERS = "richest-golfers"
    HOCKEY = "hockey"
    INTERNATIONAL = "international-celebrities"
    INDIA = "indian-celebrities"
    LAWYERS = "lawyers"
    MMA = "mma-net-worth"
    MODELS = "models"
    NBA = "nba"
    NFL = "nfl"
    OLYMPIANS = "olympians"
    POLITICIANS = "richest-politicians"
    PRESIDENTS = "presidents"
    PRODUCERS = "producers"
    RACERS = "race-car-drivers"
    RAPPERS = "rappers"
    REPUBLICANS = "republicans"
    ROCKSTARS = "rock-stars"
    ROYALS = "royals"
    SHEIKS = "sheiks"
    SINGERS = "singers"
    SKATEBOARDERS = "skateboarders"
    SOCCER = "richest-soccer"
    TENNIS = "richest-tennis"
    WALLSTREETERS = "wall-street"
    WRESTLERS = "wrestlers"